'''
Tests for a raw site generated by the siteGenerator
'''

import siteGenerator
import os
import fileinput
import sys
import filecmp

# Gets specific paths needed for testing
abspath = os.path.abspath(__file__)
dname = os.path.dirname(abspath)
sitesFolder = dname + '/sites'
testsFolder = dname + '/tests'

# Generates the site called raw under the sites folder
siteGenerator.generate_site("raw", "New_York", "sqlite3")



def test_settings():
    settingsPath = sitesFolder + "/raw/raw/settings.py"
    testSettingsPath = testsFolder + "/raw/raw/settings.py"
    
    #print settingsPath
    #print testSettingsPath
    
    settingsFile = open(settingsPath, 'r')
    testSettingsFile = open(testSettingsPath, 'r')
    
    for l1,l2 in zip(settingsFile, testSettingsFile):
        if "SECRET_KEY =" in l1:
            continue
        else:
            assert l1 == l2
        
    
    #print filecmp.cmp(settingsPath, testSettingsPath)
    
    #assert filecmp.cmp(settingsPath, testSettingsPath) == True
    

#def test_directory_hierarchy():
    
    #rawFolder = sitesFolder + "/raw"
    #rawTestFolder = testsFolder + "/raw"
    
    #comparison = filecmp.dircmp(rawFolder, rawTestFolder)
    #output = comparison.report_full_closure()
    #goldOutput = """diff /home/dylan/Desktop/site-generator/SiteGenerator/sites/raw /home/dylan/Desktop/site-generator/SiteGenerator/tests/raw
#Identical files : ['manage.py']
#Common subdirectories : ['raw']

#diff /home/dylan/Desktop/site-generator/SiteGenerator/sites/raw/raw /home/dylan/Desktop/site-generator/SiteGenerator/tests/raw/raw
#Identical files : ['__init__.py', 'settings.py', 'urls.py', 'wsgi.py']
#Common subdirectories : ['media', 'templates']

#diff /home/dylan/Desktop/site-generator/SiteGenerator/sites/raw/raw/templates /home/dylan/Desktop/site-generator/SiteGenerator/tests/raw/raw/templates

#diff /home/dylan/Desktop/site-generator/SiteGenerator/sites/raw/raw/media /home/dylan/Desktop/site-generator/SiteGenerator/tests/raw/raw/media
#None
#"""

    #print output + "this is totoal cratpp"
    #print "#######################################"
    #print goldOutput
    
    #assert output == goldOutput
    
    
def test_cleanup_raw():
    rawFolder = sitesFolder + "/raw"
    
    if os.path.exists(rawFolder):
        os.chdir(sitesFolder)
        os.system("rm -rf raw")
    
    assert os.path.exists(rawFolder) == False

